name: Base

on:
  push:
    branches: [main]
    paths:
      - "**/base.Dockerfile"
      - "**/base.yml"

env:
  REGISTRY_GH: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push-docker-image:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    strategy:
      matrix:
        distro:
          - debian
        version:
          - "trixie"
          - "bookworm"
          - "bullseye"
        variant:
          - "slim"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to Docker Hub Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Log in to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_GH }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.IMAGE_NAME }}
            ${{ env.REGISTRY_GH }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v3
        with:
          file: .docker/base.Dockerfile
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ matrix.distro }}-${{ matrix.version }}-${{ matrix.variant }}
            ${{ env.REGISTRY_GH }}/${{ env.IMAGE_NAME }}:${{ matrix.distro }}-${{ matrix.version }}-${{ matrix.variant }}
          build-args: |
            _DISTRO=${{ matrix.distro }}
            _VERSION=${{ matrix.version }}
            _VARIANT=${{ matrix.variant }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY_GH }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
